#!/usr/bin/env bash
function gnu_generic_getopts() {
  declare -gA OPTIONS
  declare -ga ARGUMENTS=()

  if [[ "${2:-}" == "--help" ]]; then
    OPTIONS[help]=true
    shift 2
    ARGUMENTS=("$@")
    return
  fi

  if [[ "$1" == "-" ]]; then
    exec 6< <(cat)
  else
    local app="${1:?The function parse_gnu_help requires a function/command which outputs the GNU-compatibled help message}";
    exec 6< <("$app")
  fi
  shift

  if [[ $# -eq 1 ]] && [[ "$1" == "--shebang "?* ]]; then
      local -a args
      [[ -n "${BASH_VERSION:-}" ]] && read -r -a args <<< "${1#--shebang }"
      [[ -n "${ZSH_VERSION:-}" ]] && read -r -A args <<< "${1#--shebang }"
      set -- "${args[@]}"
  fi

  local opt="" val="" optstring=""
  typeset -a extra_long_opts
  typeset -A options_map

  local split="(\\ \\ |	|[[:blank:]]*\$)"
  local name_regex='[a-zA-Z0-9][-_a-zA-Z0-9]*[a-zA-Z0-9]+'
  local short_opt_regex="-[a-zA-Z0-9]"
  local long_opt_regex="--$name_regex"
  local single_arg_regex='[a-zA-Z0-9][^[:blank:]]+'
  local args_regex="${single_arg_regex},?(\\[[^]]*\\.\\.\\.[^]]*\\])?"
  local multi_args_regex="${single_arg_regex},?\\[[^]]*\\.\\.\\.[^]]*\\]"

  while read -r -u 6 line; do
    local short_opt='' long_opt='' opt_arg=''
    if [[ "$line" =~ ^$short_opt_regex$split ]]; then
      #debug : -h : single opt: $line
      short_opt="${line%%  *}"
      short_opt="${short_opt%%	*}"
    elif [[ "$line" =~ ^$long_opt_regex$split ]]; then
      #debug : --help : long opt: $line
      long_opt="${line%%  *}"
      long_opt="${long_opt%%	*}"
    elif [[ "$line" =~ ^$short_opt_regex,\ $long_opt_regex$split ]]; then
      #debug : -h, --help : single and long opt: $line
      short_opt="${line%%, *}"
      long_opt="${line:4}"
      long_opt="${long_opt%%  *}"
      long_opt="${long_opt%%	*}"
    elif [[ "$line" =~ ^$short_opt_regex\ $args_regex$split ]]; then
      #debug : -d DOMAIN : single opt require argument: $line
      short_opt="${line%% *}"
      opt_arg="${line#* }"
    elif [[ "$line" =~ ^$long_opt_regex=$args_regex$split ]]; then
      #debug : --tags=TAG[TAG,...] : long opt, require argument: $line
      long_opt="${line%%=*}"
      opt_arg="${line#*=}"
    elif [[ "$line" =~ ^$short_opt_regex,\ $long_opt_regex=$args_regex$split ]]; then
      #debug : -t, --tags=TAG,[TAG,...] : single and long opt, require argument: $line
      short_opt="${line%%, *}"
      long_opt="${line:4}"
      long_opt="${long_opt%%=*}"
      opt_arg="${line#*=}"
    else
      continue # non-option lines
    fi
    short_opt="${short_opt#-}"
    long_opt="${long_opt#--}"
    if [[ "$opt_arg" =~ ^$multi_args_regex$split ]]; then
      #debug multi: $opt_arg
      opt_arg="+"
    elif [[ "$opt_arg" =~ ^$single_arg_regex$split ]]; then
      #debug single: $opt_arg
      opt_arg="="
    fi

    if [[ -n "$long_opt" ]]; then
      options_map[${long_opt}]="${long_opt}${opt_arg}"
      [[ -n "$short_opt" ]] && options_map[$short_opt]="${long_opt}${opt_arg}"
    else
      options_map[$short_opt]="${short_opt}${opt_arg}"
    fi

    if [[ -n "$short_opt" ]]; then
      #info "short opt: ${short_opt}"
      optstring="${optstring}${short_opt}"
      [[ -n "$opt_arg" ]] && optstring="${optstring}:"
    elif [[ -n "$long_opt" ]]; then
      extra_long_opts+=("$long_opt")
    fi
    #[[ -n "$long_opt" ]] && info "long opt: ${long_opt}"
  done
  #echo ""
  #debug optstring="$optstring"
  #typeset -p extra_long_opts
  #debug "$(typeset -p options_map)"
  #info "$@"
  declare -a standard_params
  while param="${1:-}"; [[ -n "$param" ]]; do
    shift
    if [[ "$param" == "--" ]]; then
      standard_params+=("--" "$@")
      break;
    elif [[ "$param" == "-"[a-zA-Z0-9]?* ]] && [[ "${options_map[${param:1:1}]:-}" != *[=+] ]]; then
      for (( i=1; i<${#param}; i++ )); do
        standard_params+=("-${param:$i:1}")
      done
    else
      standard_params+=("$param")
    fi
  done
  #debug "${standard_params[@]}"
  set -- "${standard_params[@]}"
  local retval=0
  while param="${1:-}"; [[ -n "$param" ]]; do
    shift
    local val='' opt='' boolopt='' appendopt=''
    if [[ "$param" == "--" ]]; then
      ARGUMENTS+=("$@")
      break;
    elif [[ "$param" == "-"* ]]; then
      #debug "$param"
      opt="${param#-}"
      if [[ "${opt}" == "${opt#-}" ]] && [[ "${#opt}" -gt 2 ]]; then
        val="${opt#?}"
        opt="${opt:0:1}"
      else
        opt="${opt#-}"
      fi
      if [[ "$opt" == *"="* ]]; then
        val="${opt#*=}"
        opt="${opt%%=*}"
      fi
      local optkey="${options_map[$opt]:-}"
      if [[ -z "$optkey" ]]; then
        err "Invalid option '$param'."
        val=""
        retval=1
      elif [[ "$optkey" == *[=+] ]]; then
        [[ -z "$val" ]] && val="${optkey:((${#optkey}-1)):1}"
        [[ "$optkey" == *"+" ]] && appendopt=yes
        optkey="${optkey%?}"
      else
        boolopt=yes
        [[ -z "$val" ]] && val=true
      fi
      if [[ -n "$boolopt" ]] && [[ -n "$val" ]]; then
        declare -l val="$val"
        if [[ "$val" == yes ]] || [[ "$val" == true ]]; then
          val=true
        else
          val=false
        fi
      fi
      if [[ "$val" == [=+] ]]; then
        local val="${1:-}"
        [[ "$val" == "-"* ]] && val=
        if [[ -z "$val" ]]; then
          optkey=
          err option "'$param'" requires an argument.
          retval=1
          #break
        else
          shift
        fi
      fi
      [[ -n "$optkey" ]] && if [[ -n "$appendopt" ]] && [[ -n "${OPTIONS[$optkey]:-}" ]]; then
        OPTIONS[$optkey]="${OPTIONS[$optkey]},${val}"
      else
        OPTIONS[$optkey]="${val}"
      fi
      #debug "$OPTIONS[$optkey]=${val@Q}"
    else
      ARGUMENTS+=("${param}")
    fi
  done
  #declare -p OPTIONS >&2
  return "$retval"
} &>/dev/null

[[ -z "${ZSH_VERSION:-}" ]] && return

gnu_generic_getopts "$@"

# vi: set shiftwidth=2 :
# vi: set tabstop=2 :
