version: 2.1

jobs:
  test-on-linux:
    docker:
      - image: buildpack-deps:trusty
    steps: &steps
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./run-tests.sh
#   test-on-macos:
#     macos:
#       xcode: "11.1.0"
#     steps: *steps

workflows:
  version: 2
  test:
    jobs:
      - test-on-linux
#      - test-on-macos

