version: 2.1

jobs:
  test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: ./run-tests.sh
