name: Testing

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Test Shell Common Functions Library
      run: ./run-tests.sh
