name: Testing

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: yes
    - name: Test Shell Common Functions Library
      run: ./run-tests.sh
