name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Test Shell Common Functions Library
      run: ./run-tests.sh
